export const REMOVE_CONTACT = 'REMOVE_CONTACT'
export const ADD_CONTACT = 'ADD_CONTACT'
export const CHANGE_FILTER = 'CHANGE_FILTER'
export const ADD_TO_FAVORITE = 'ADD_TO_FAVORITE'
export const EDIT_CONTACT = 'EDIT_CONTACT'
export const CHANGE_VALUE = 'CHANGE_VALUE'


